# This compose file is not suited for production. It is intended for
# development.

version: "3.7"

services:
  testy:
    image: testy
    build: .
    restart: on-failure
    environment:
      - DEBUG=${DEBUG:-True}
      - MONGO_DB=${MONGO_DB:-fhirstore}
      - MONGO_HOST=${MONGO_HOST:-mongo}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_USER=${MONGO_USER:-arkhn}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS_EXTERNAL=${KAFKA_BOOTSTRAP_SERVERS_EXTERNAL}
      - PYROG_API_HOST=${PYROG_API_HOST:-pyrog-server}
      - RIVER_API_HOST=${RIVER_API_HOST:-river-api}

networks:
  default:
    external:
      name: ${NETWORK:-arkhn_network}
