# This compose file is not suited for production. It is intended for
# development.

version: "3.7"

services:
  testy:
    image: testy
    build: .
    restart: on-failure
    environment:
      - DEBUG=${DEBUG:-True}
      - MONGO_DB=${MONGO_DB:-fhirstore}
      - MONGO_HOST=${MONGO_HOST:-mongo}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_USER=${MONGO_USER:-arkhn}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - KAFKA_HOST=${KAFKA_HOST:-kafka}
      - KAFKA_PORT=${KAFKA_PORT:-9092}
      - KAFKA_PROTO=${KAFKA_PROTO:-PLAINTEXT}
      - PYROG_API_HOST=${PYROG_API_HOST:-pyrog-server}
      - PYROG_API_PORT=${PYROG_API_PORT:-1000}
      - RIVER_API_URL=${RIVER_API_URL:-river-api:8000}
      - RIVER_REDIS_HOST=${RIVER_REDIS_HOST:-river-redis}
      - RIVER_REDIS_PORT=${RIVER_REDIS_PORT:-6379}
      - REDIS_COUNTER_DB=${REDIS_COUNTER_DB:-2}

networks:
  default:
    external:
      name: ${NETWORK:-arkhn_network}
