[tool.isort]
atomic = true
combine_star = true
default_section = "FIRSTPARTY"
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
indent = 4
known_arkhn = "fhirstore"
known_first_party = ""
known_third_party = "confluent_kafka,pymongo,pytest,requests"
line_length = 88
multi_line_output = 3
sections = "FUTURE,STDLIB,THIRDPARTY,ARKHN,FIRSTPARTY,LOCALFOLDER"
skip_gitignore = true
use_parentheses = true

[tool.black]
exclude = '''
(
    \.git
    | \.tox
    | \.venv
    | \.venv
    | __pycache__
)
'''
target-version = ["py38"]
