name: testy

on: push

jobs:
  tests:
    runs-on: ubuntu-18.04

    steps:
      - name: Provision, deploy and test
        uses: arkhn/testy-action@v0.3.0
        with:
          cloudToken: ${{ secrets.CLOUD_TOKEN }}
          cloudProjectId: ${{ secrets.CLOUD_PROJECT_ID }}
          cloudKey: ${{ secrets.CLOUD_KEY }}
          contextName: testy-repo-${{ github.sha }}
          deploymentToken: ${{ secrets.DEPLOYMENT_DEPLOY_KEY }}
          deploymentRef: sv/config-e2e-tests
